### ISSUE TITLE
SSR - document is not defined

### ISSUE THREAD

**Issue by AaronTee** [kherP/css-style-inject#1]
**What went wrong**
One of our project is developed using Nextjs framework with SSR, upon rendering on server side, an error was being thrown from css-style-inject.

By looking at the code it seems like the document object exist checking was done only after document.querySelector call, hence runtime error occurred.
https://github.com/kherP/css-style-inject/blob/main/lib/injectCSS.ts

May need to check detachCSS method as well.

**Comment by kherP** [comment]
fixed in release 1.1.2
